# Generated by Django 4.2 on 2024-04-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
