# Generated by Django 4.2 on 2024-02-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='document_namely',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hujjat nomlanishi'),
        ),
    ]
