# Generated by Django 4.2 on 2024-02-08 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0002_alter_corpus_parent'),
        ('core', '0002_article_creator_book_creator_internetinfo_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Uslub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('word_qty', models.PositiveIntegerField(default=0, verbose_name="So'z miqdori")),
                ('sentence_qty', models.PositiveIntegerField(default=0, verbose_name='Gap miqdori')),
                ('text', models.TextField(verbose_name='Matn')),
                ('file', models.FileField(blank=True, null=True, upload_to='core/')),
                ('source_type', models.CharField(choices=[('newspaper', 'newspaper'), ('official_text', 'official_text'), ('journal', 'journal'), ('internet_info', 'internet_info'), ('book', 'book'), ('article', 'article'), ('other', 'other')], max_length=17, verbose_name='Manba turi')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nashr raqami')),
                ('net_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='NET-manzili')),
                ('theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Matn mavzusi')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Muallif')),
                ('author_type', models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman')], max_length=5, null=True, verbose_name='Muallif jinsi')),
                ('wrote_at', models.DateTimeField(blank=True, null=True, verbose_name='Yozilgan vaqti')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr yili')),
                ('auditorium_age', models.CharField(blank=True, max_length=10, null=True, verbose_name='Auditoriya yoshi')),
                ('document_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hujjat turi')),
                ('document_owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hujjat chiqargan tashkilot (shaxs)')),
                ('publisher', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nashriyoti')),
                ('text_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adadi')),
                ('issn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISSN')),
                ('authors', models.TextField(blank=True, null=True, verbose_name='Mualliflar ismi, jinsi, yillari')),
                ('time_and_place_of_the_event', models.CharField(blank=True, max_length=500, null=True, verbose_name='Voqea vaqti va joyi')),
                ('article_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Chop etilgan vaqti')),
                ('pages_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sahifalari')),
                ('name_of_article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manbaning (jurnal, kitob) nomi')),
                ('corpus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.corpus', verbose_name='Korpus turi')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('field_of_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fieldofapplication', verbose_name="Qo'llanish sohasi")),
                ('level_of_auditorium', models.ManyToManyField(blank=True, to='core.capacityleveloftheauditorium', verbose_name='Auditoriya salohiyat darajasi')),
                ('literary_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.literarygenre', verbose_name='Adabi turi')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.style', verbose_name='Uslubi')),
                ('text_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.texttype', verbose_name='Matn tipi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='book',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='book',
            name='field_of_application',
        ),
        migrations.RemoveField(
            model_name='book',
            name='level_of_auditorium',
        ),
        migrations.RemoveField(
            model_name='book',
            name='literary_genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='text_type',
        ),
        migrations.RemoveField(
            model_name='internetinfo',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='internetinfo',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='internetinfo',
            name='field_of_application',
        ),
        migrations.RemoveField(
            model_name='internetinfo',
            name='level_of_auditorium',
        ),
        migrations.RemoveField(
            model_name='internetinfo',
            name='text_type',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='level_of_auditorium',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='text_type',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='level_of_auditorium',
        ),
        migrations.RemoveField(
            model_name='officialtext',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='officialtext',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='othermetadata',
            name='book_ptr',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='InternetInfo',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='OfficialText',
        ),
        migrations.DeleteModel(
            name='OtherMetaData',
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.text',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.text',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.text',),
        ),
        migrations.CreateModel(
            name='InternetInfo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.text',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.text',),
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.text',),
        ),
        migrations.CreateModel(
            name='OfficialText',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.text',),
        ),
    ]
