# Generated by Django 4.2 on 2024-02-10 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_text_document_namely'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='literary_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.literarygenre', verbose_name='Adabiy turi'),
        ),
    ]
