# Generated by Django 4.2 on 2024-02-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_creator_book_creator_internetinfo_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Uslub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.style', verbose_name='Uslubi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.style', verbose_name='Uslubi'),
        ),
        migrations.AlterField(
            model_name='internetinfo',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.style', verbose_name='Uslubi'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.style', verbose_name='Uslubi'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.style', verbose_name='Uslubi'),
        ),
    ]
