# Generated by Django 4.2 on 2024-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_style_alter_article_style_alter_book_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='core/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='core/'),
        ),
        migrations.AlterField(
            model_name='internetinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='core/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='core/'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='core/'),
        ),
        migrations.AlterField(
            model_name='officialtext',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='core/'),
        ),
    ]
