# Generated by Django 4.2 on 2024-02-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_text_literary_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ISBN'),
        ),
    ]
