# Generated by Django 4.2 on 2024-02-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_text_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Matn'),
        ),
    ]
