# Generated by Django 4.2 on 2024-03-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_phrase_word_wordsemanticexpression_wordgrammar'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lemma',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
