# Generated by Django 4.2 on 2024-03-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_createwordfromexcel_word_excel_file_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='createwordfromexcel',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
