# Generated by Django 4.2 on 2024-03-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_createwordfromexcel_uuid_word_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='excel_file_obj',
        ),
    ]
